// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { InvestmentRound$Type } from "./InvestmentRound";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["InvestmentRound"]: InvestmentRound$Type;
    ["contracts/InvestmentRound.sol:InvestmentRound"]: InvestmentRound$Type;
  }

  interface ContractTypesMap {
    ["InvestmentRound"]: GetContractReturnType<InvestmentRound$Type["abi"]>;
    ["contracts/InvestmentRound.sol:InvestmentRound"]: GetContractReturnType<InvestmentRound$Type["abi"]>;
  }
}
